services:
  application:
    container_name: vidwiz-app
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: vidwiz-db
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: