services:
  application:
    container_name: vidwiz-app
    image: adhirajpandey/vidwiz:latest
    env_file:
      - .env
    environment:
      - RATELIMIT_STORAGE_URI=memcached://vidwiz-cache:11211
    restart: unless-stopped
    ports:
      - "5006:5000"
    depends_on:
      - database
      - vidwiz-cache

  database:
    image: postgres:15
    container_name: vidwiz-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  vidwiz-cache:
    image: memcached:1.6
    container_name: vidwiz-cache
    restart: unless-stopped
    command: memcached -m 64 -p 11211

volumes:
  pgdata:
