services:
  application:
    container_name: vidwiz-app
    image: adhirajpandey/vidwiz:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5006:5000"
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: vidwiz-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
