"""
Configuration for VidWiz application.
"""

TRANSCRIPT_TASK_REQUEST_DEFAULT_TIMEOUT = 30
TRANSCRIPT_TASK_REQUEST_MAX_TIMEOUT = 60
TRANSCRIPT_POLL_INTERVAL = 2

FETCH_TRANSCRIPT_TASK_TYPE = "fetch_transcript"
FETCH_TRANSCRIPT_MAX_RETRIES = 3
FETCH_TRANSCRIPT_IN_PROGRESS_TIMEOUT = 120

S3_BUCKET_NAME = "vidwiz"

# Metadata task configuration
FETCH_METADATA_TASK_TYPE = "fetch_metadata"
FETCH_METADATA_MAX_RETRIES = 3
FETCH_METADATA_IN_PROGRESS_TIMEOUT = 120

METADATA_TASK_REQUEST_DEFAULT_TIMEOUT = 30
METADATA_TASK_REQUEST_MAX_TIMEOUT = 60
METADATA_POLL_INTERVAL = 2

# Summary task configuration
GENERATE_SUMMARY_TASK_TYPE = "generate_summary"
