TRANSCRIPT_TASK_REQUEST_DEFAULT_TIMEOUT = 30
TRANSCRIPT_TASK_REQUEST_MAX_TIMEOUT = 60
TRANSCRIPT_POLL_INTERVAL = 2

FETCH_TRANSCRIPT_TASK_TYPE = "fetch_transcript"
FETCH_TRANSCRIPT_MAX_RETRIES = 3
FETCH_TRANSCRIPT_IN_PROGRESS_TIMEOUT = 120

FETCH_METADATA_TASK_TYPE = "fetch_metadata"
FETCH_METADATA_MAX_RETRIES = 3
FETCH_METADATA_IN_PROGRESS_TIMEOUT = 120

METADATA_TASK_REQUEST_DEFAULT_TIMEOUT = 30
METADATA_TASK_REQUEST_MAX_TIMEOUT = 60
METADATA_POLL_INTERVAL = 2

TASK_TYPE_MAP = {
    "transcript": FETCH_TRANSCRIPT_TASK_TYPE,
    "metadata": FETCH_METADATA_TASK_TYPE,
}
