TASK_REQUEST_DEFAULT_TIMEOUT = 30
TASK_REQUEST_MAX_TIMEOUT = 60
TASK_POLL_INTERVAL = 2
TASK_MAX_RETRIES = 3
TASK_IN_PROGRESS_TIMEOUT = 120

FETCH_TRANSCRIPT_TASK_TYPE = "fetch_transcript"
FETCH_METADATA_TASK_TYPE = "fetch_metadata"

TASK_TYPE_MAP = {
    "transcript": FETCH_TRANSCRIPT_TASK_TYPE,
    "metadata": FETCH_METADATA_TASK_TYPE,
}
