name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          password: ${{ secrets.RPI_PASSWORD }}
          port: 22
          proxy_host: ${{ secrets.EC2_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_REPO_PATH }} && git pull
            cp ${{ secrets.SERVER_REPO_PATH }}/projects/vidwiz/.env ${{ secrets.VIDWIZ_REPO_PATH }}/.env
            cd ${{ secrets.VIDWIZ_REPO_PATH }} && git pull
            docker compose down
            docker rmi vidwiz_app:latest || true
            docker compose up -d --build