name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: adhirajpandey/vidwiz:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          password: ${{ secrets.RPI_PASSWORD }}
          port: 22
          proxy_host: ${{ secrets.EC2_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_REPO_PATH }} && git pull
            cp ${{ secrets.SERVER_REPO_PATH }}/projects/vidwiz/.env ${{ secrets.VIDWIZ_REPO_PATH }}/.env
            cd ${{ secrets.VIDWIZ_REPO_PATH }} && git pull
            docker pull adhirajpandey/vidwiz:latest
            docker compose -f docker-compose.prod.yml down || true
            docker compose -f docker-compose.prod.yml up -d
            