name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ytnotes:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ytnotes:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_REPO_PATH }} && git pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ytnotes:latest
            docker rm -f ytnotes-app || true
            docker run --env-file ${{ secrets.SERVER_REPO_PATH }}/projects/YT-Notes/.env -d --name ytnotes-app -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/ytnotes:latest
            docker image prune -f